### ISSUE TITLE
Debugger doesn’t work properly

### ISSUE THREAD

**Issue by artoka315** [ZiYueCommentary/Blitz3D#13]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/ZiYueCommentary/Blitz3D/issues) before.
- [X] This bug still exists in the latest version of the Blitz3D TSS.

### Describe the Bug

When I use the debugger for IDEal and BlitzIDE, it closes automatically.

### Related codes

None

### Reproduction Steps

1. Open Blitz3D
2. Use the debugger

### Caught Exception

None

### Operating System

Windows 10

**Comment by ZiYueCommentary** [comment]
This issue does not reproduce successfully. Requires further validation.
