### ISSUE TITLE
Games fail to launch on Linux via Proton starting from version 1.126

### ISSUE THREAD

**Issue by VaneBrain** [ZiYueCommentary/Blitz3D#16]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/ZiYueCommentary/Blitz3D/issues) before.
- [X] This bug still exists in the latest version of the Blitz3D TSS.

### Describe the Bug

Although Blitz3D TSS does not natively support the Linux operating system, many users have successfully run games using Proton. However, starting from version 1.126, games no longer launch on Linux.

### Related codes

SCP: Nine-Tailed Fox code can be used to test this issue: https://github.com/VaneBrain/scpntf

### Reproduction Steps

1. Start any Blitz3D TSS games on Linux system.

### Caught Exception

Memory Access Violation

### Operating System

Arch Linux x86_64

### Extra Information

Games, compiled on version 1.125, were proven to run fine on Linux (and Steam Deck).

**Comment by I8aDOG** [comment]
Really hoping this issue is discovered and fixed, disappointing I can't play neither SCP Ultimate Edition and Nine-Tailed Fox on my Linux desktop, especially now that I main drive it to play games.

**Comment by ZiYueCommentary** [comment]
I can't fix it by myself because I can't build the environment properly. Need someone who can run the program for testing.

**Comment by ZiYueCommentary** [comment]
After debugging with @I8aDOG , the result is that incompatible is caused by the default font which the engine loads when initializing. I think we need a solution to reserve the default font, since default font is very convenient, especially for small programs.
