### ISSUE TITLE
Vote: Remove Installer

### ISSUE THREAD

**Issue by ZiYueCommentary** [ZiYueCommentary/Blitz3D#17]
[Installer](https://github.com/ZiYueCommentary/Blitz3D/releases/download/v1.131/Installer.exe) for Blitz3D TSS is useless and very complex to build when releasing a new version. Though I like it very much, it doesn't have any reason to keep it existing.

I'm planning to remove this thing from Blitz3D TSS. Please vote with the reactions down below to show your opinion. Thank you.

**Comment by VaneBrain** [comment]
As long as it is easy and fast to install Blitz3D TSS from archive (and run it afterwards), I don't see really the need for installer.

Perhaps the installer is doing something else too? Maybe it sets environmental paths? I haven't checked that, but I doubt it does it.

**Comment by ZiYueCommentary** [comment]
> As long as it is easy and fast to install Blitz3D TSS from archive (and run it afterwards), I don't see really the need for installer.
> 
> Perhaps the installer is doing something else too? Maybe it sets environmental paths? I haven't checked that, but I doubt it does it.

It associates `.bb` with Blitz3D, and that's almost all.

**Comment by VaneBrain** [comment]
> It associates `.bb` with Blitz3D, and that's almost all.
While it is a little useful feature, I feel like many people can set up .bb files manually on their PC.
