### ISSUE TITLE
Displaying Non-English Characters

### ISSUE THREAD

**Issue by hlpdev** [ZiYueCommentary/Blitz3D#2]
Hi, I'm working on a project at the moment and I'm working on a Localization system. I'm having issues displaying non english characters (ex: "ЗАПУСК") 

I've been trying to figure out the issue for a couple of days, going through different fonts, builds of Blitz3D, etc but have not found a way to do this. 

If you could help me or lead me in the right direction that would be amazing. Thanks

**Comment by ZiYueCommentary** [comment]
Closed as solved.
