### ISSUE TITLE
关于FreeFont无法使用的问题

### ISSUE THREAD

**Issue by MorningDemon515** [ZiYueCommentary/Blitz3D#4]
https://github.com/ZiYueCommentary/Blitz3D/blob/2b1648e65316ba6bafbfdcc56ee18ed0d2354d13/gxruntime/gxgraphics.cpp#L264

这行代码里Mark使用了.erase函数去删除字体，但是这是没用的，juanjp600使用了freetype，在freetype里加载字体有两种方法:

1.从字体文件名
2.从内存

不过从代码:

https://github.com/ZiYueCommentary/Blitz3D/blob/2b1648e65316ba6bafbfdcc56ee18ed0d2354d13/gxruntime/gxfont.cpp#L12

可以明显看出，juanjp600用的是字体文件名加载，所以，要想FreeFont起作用，只能用FT_Done_Face函数去试试，否则你只能不调用这个函数

**Comment by ZiYueCommentary** [comment]
`erase`函数所属于的对象是“font_set”，是Blitz3D内部用于统计已加载字体对象的列表。FreeFont中的erase用于把指定的字体从列表中删掉，意味着该字体资源已不可用，**但不代表字体资源被回收**。

FreeFont在引擎中不负责回收资源，只负责给资源加“被回收”的标记。字体资源在程序退出时会被调用`gxFont`中的析构函数，以便于回收资源，而该函数中有FT_Done_Face。

最后，“要想FreeFont有用就要调用函数，否则就不要用”，意思是不用FreeFont，FreeFont就有作用了？

**Comment by MorningDemon515** [comment]
那就把FreeFont这个函数删了吧，反正也用不了

**Comment by ZiYueCommentary** [comment]
因为FreeFont没有按照你想要的方式去工作，所以就没有用，就要被删掉？

**Comment by ZiYueCommentary** [comment]
FreeFont即使没有真正意义上“Free”掉字体，但在游戏引擎里，被“Free”的字体已经不能调用了，效果跟彻底回收资源是一样的。

况且引擎不是不回收资源，只是在程序结束后一起回收资源，你就要这么锱铢必较吗。

**Comment by MorningDemon515** [comment]
可这个函数在游戏中都无法正常运行，现在又无法被救活，那只能被删掉了

**Comment by MorningDemon515** [comment]
https://github.com/ZiYueCommentary/Blitz3D/blob/2b1648e65316ba6bafbfdcc56ee18ed0d2354d13/gxruntime/gxgraphics.cpp#L264
等等，那个"delete f"才是删掉函数的部分?

**Comment by ZiYueCommentary** [comment]
尼玛的我被你带坑里去了

delete f就是删资源，调用对象的析构函数，你要是真看不懂C++就别发issue了

**Comment by MorningDemon515** [comment]
那把delete改用FT_Done_Face试试?

**Comment by ZiYueCommentary** [comment]
你这点问题私信我就行，不要发Issue让别人来看笑话。

**Comment by MorningDemon515** [comment]
歪果仁看不懂中文(乐)

**Comment by ZiYueCommentary** [comment]
我都能想象到义贼哥看到这个issue会笑成什么样

**Comment by EasyT-T** [comment]
> 我都能想象到义贼哥看到这个issue会笑成什么样

你猜
